# -*- coding: utf-8 -*-
"""PythonProblem11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vweSUy3j7kzQLJIA4Haa4mOzjnehwoQV

Problem 11: Check if string has length more than 10 character, if it is then divide it in two parts and print it on console.  
Solution:
"""

#Assigning value to a string
String = "Nothing is impossible"

#Checking if string has more than 10 characters then dividing it into 2 parts
if len(String)>10:
  # Using string slicing 
  #Splitting string into equal halves
  res_first, res_second = String[:len(String)//2], String[len(String)//2:]

print(res_first)
print(res_second)

