# -*- coding: utf-8 -*-
"""PythonProblem7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YT1qdCnLxQUqdXY9FXsKXigKMYDLWPHE

Problem 7: To find common numbers and different numbers from 2 files containing numbers seperated by new line    
Solution:
"""

#Uploading file of numbers
from google.colab import files
uploaded = files.upload()

#Reading files and storing data into data1 and data2
import pandas as pd
with open("integers.txt","r") as f:
  data1 = f.readlines()
with open("integers2.txt","r") as f:
  data2 = f.readlines()

#Storing numerical string data into lists by removing new line characters
l1 =[]
l2 =[]
for i in data1:
  l1.append(i.strip())
for i in data2:
  l2.append(i.strip())

print(l1)
print(l2)

#Retrieving common and different numbers from 2 lists
comm = "Common Numbers are : "
diff = "Different Numbers are : "
c = set(l1).intersection(l2)
for i in c:
  comm = comm + i + "\t"

d = [i for i in l1 + l2 if i not in l1 or i not in l2]
for i in d:
  diff = diff + i + "\t"

print(comm)
print(diff)

