# -*- coding: utf-8 -*-
"""PythonProblem4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Sgr74umsTv7Rp7TDiNdZGk5iZ2GD_Ol

Problem 4: Remove punctuations and convert text in lowercase then perform word count  
Solution:
"""

# import OS module
import os

# Get the list of all files and directories
path = "/content/sampletxts"
dir_list = os.listdir(path)
  
print("Files and directories in '", path, "' :")
  
# prints all files
print(dir_list)

#Total number of word counts of every file
for x in dir_list:
  file = open(path + '/' + x , "rt")
  data = file.read()
  words = data.split()
  print('Number of total words in ' + x + ':', len(words))

#Function which will remove punctuation and convert the text into lowercase
def remove_punctuation(text):
  punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

   # remove punctuation from the text
  no_punct = ""
  for char in text:
     if char not in punctuations:
         no_punct = no_punct + char

  no_punct = no_punct.lower()
  # return the unpunctuated string
  return(no_punct)

temp = ""
#Loop through every file in a directory
for x in dir_list:
  text = open(path + '/' + x , "rt")
  d = dict()
  
  # Loop through each line of the file
  for line in text:
    # Remove the leading spaces and newline character
    line = line.strip()
  
    # Calling function
    line = remove_punctuation(line)
  
    # Split the line into words
    words = line.split(" ")
  
    # Iterate over each word in line
    for word in words:
      # Check if the word is already in dictionary
      if word in d:
        # Increment count of word by 1
        d[word] = d[word] + 1
      else:
        # Add the word to dictionary with count 1
        d[word] = 1
  
  #adding dictionary keys and values to string 
  for key in list(d.keys()):
    temp = temp + key + "," + str(d[key]) + '\n'

  temp = temp + "\n\n\n\n"  

#writing a new file with a string which is having all file's words and its occurance counts    
with open('/content/Empty.txt', 'w') as writefile:
    writefile.write(temp)

#Reading that new file having words and their occurances of all files without punctuations
with open('/content/Empty.txt', 'r') as readfile:
    print(readfile.read())

