# -*- coding: utf-8 -*-
"""PythonProblem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ygRj3eAX1dy6_88OTu586x4m1RMrScyn

Problem 1: Count occurance of each word in a text from a static text         
Solution:
"""

text = " Hello World How are you World Hello"

# Create an empty dictionary
d = dict()
  
# Remove the leading spaces and newline character
text = text.strip()
  
# Convert the characters into lowercase to avoid case mismatch 
text = text.lower()
  
# Split the line into words
words = text.split(" ")
  
# Iterate over each word in line
for word in words:
  # Check if the word is already in dictionary
  if word in d:
    # Increment count of word by 1
    d[word] = d[word] + 1
  else:
    # Add the word to dictionary with count 1
    d[word] = 1

# Print the contents of dictionary
for key in list(d.keys()):
    print(key, ":", d[key])

