# -*- coding: utf-8 -*-
"""PythonProblem10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15hLFFwmlsAPEApEA62wQtewfBCO1YTrt

Problem 10: Print characters at even index in string  
Solution:
"""

#Assigning string a value
String = "Welcome to the future"

#Appending characters at even index to an empty string
evenstr = ""
for i in range(0,len(String)):
  if i%2==0:
    evenstr = evenstr + String[i]
evenstr

