# -*- coding: utf-8 -*-
"""PythonProblem2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XvYgaAUwwMlMiZkt6NZr6fful0YfszzQ

Problem 2: Count occurance of each word in a text from a file path and write it into a new file   
Solution:
"""

from google.colab import files
uploaded = files.upload()

# Create an empty dictionary
# Open the file in read mode
text = open("sample2.txt", "r")
d = dict()
  
# Loop through each line of the file
for line in text:
  # Remove the leading spaces and newline character
  line = line.strip()
  
  # Convert the characters in line to 
  # lowercase to avoid case mismatch
  line = line.lower()
  
  # Split the line into words
  words = line.split(" ")
  
  # Iterate over each word in line
  for word in words:
    # Check if the word is already in dictionary
    if word in d:
      # Increment count of word by 1
      d[word] = d[word] + 1
    else:
      # Add the word to dictionary with count 1
      d[word] = 1
  
# Print the contents of dictionary
for key in list(d.keys()):
    print(key, ":", d[key])

temp = ""
for key in list(d.keys()):
    temp = temp + key + "," + str(d[key]) + '\n'
print(temp)

with open('/content/Empty.txt', 'w') as writefile:
    writefile.write(temp)

with open('/content/Empty.txt', 'r') as readfile:
    print(readfile.read())

