# -*- coding: utf-8 -*-
"""PythonProblem12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kEZV7lKw-QQxaOfLJK9YR0Tqa7RUpqJW

Problem 12: Perform matrix multiplication for given two matrix if possible or raise custom error 'ImproperMatrixShape'. Don't use any library for matrix multiplication    
Solution:
"""

#Taking a 3x3 matrix
A = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
  
#Taking a 3x4 matrix    
B = [[5, 1, 0, 2],
    [2, 0, 1, 4],
    [3, 1, 2, 0]]

#Taking a 3x4 zero matrix      
result= [[0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0,0]]

if len(A)==len(B[0]):

  # iterating by row of A
  for i in range(len(A)):
  
      # iterating by coloum by B 
      for j in range(len(B[0])):
  
          # iterating by rows of B
          for k in range(len(B)):
              result[i][j] += A[i][k] * B[k][j]
else:
  print("ImproperMatrixShape")
  
for r in result:
    print(r)

